
  Mohammed Salah
  version: '3'

  services:
    api:
      build:
        context: .
        dockerfile: Dockerfile
      image: api
      ports:
        - 8080:8080
      container_name: api
      depends_on:
        - database
      restart: unless-stopped
      environment:
        MONGODB_URL: mongodb://voucher-user:voucher-password@database:27017/voucherDB
        NODE_ENV: local

    database:
      image: mongo
      restart: always
      ports:
        - '27018:27017'
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin-password
        MONGO_INITDB_DATABASE: admin
      volumes:
        - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


  networks:
    default:
      external:
        name: voucher-network